# Basic Information 
title: Haoyu (Henry) Wang
position: Postdoctoral Research Associate
affiliation: University of Oxford
email: henry.wang (at) eng.ox.ac.uk

# Search Engine Optimization (SEO)
keywords: computer architecture, confidential computing, memory hierarchy, deep learning accelerator, NoC security, hardware security
description: Dr. Haoyu Wang is a Postdoctoral Research Associate at University of Oxford, specializing in secure computer architecture, memory hierarchy, confidential computing and deep-learning accelerators.
canonical: https://henryinuk.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=YOUR_ID
cv_link: assets/files/Haoyu_Wang_CV.pdf
github_link: https://github.com/HenryINUK
linkedin: https://www.linkedin.com/in/haoyu-wang-imperial

# Images (e.g., your profile picture and your website's favicon) 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif"

# Google Analytics ID (remove this line if you don't use it)
# google_analytics: UA-XXXXXXXX-X
